### ISSUE TITLE
Manual Payment gateway does not seem to work

### ISSUE THREAD

**Issue by rvoigtfv** [zeen101/leaky-paywall#110]
It says in the log:
= 4.18.3 =
* Add a manual payment gateway as the default

However, when I try to set up a subscription with both Paypal and Manual Payment checked as gateways, only Paypal shows up in the frontend.
Also, I found that the Manual Payment class is more or less empty?
https://github.com/zeen101/leaky-paywall/blob/master/include/gateways/class-leaky-paywall-payment-gateway-manual.php

So I understand, this feature is not yet implemented ... ?

**Comment by greenhornet79** [comment]
The manual payment gateway was added and set as the default so that a publisher could test out a paid level when setting up Leaky Paywall without needing payment gateway credentials for either PayPal or Stripe.  

We also had publishers who only took payment by check, so a manual payment gateway satisfied their requirement.

Allowing subscribers to choose between "pay by check" and a payment gateway is a new request.  We will add it to our feature request list.
